### ISSUE TITLE
deps/api.cc includes <string> instead of <string.h>.

### ISSUE THREAD

**Issue by eddyb** [yorkie/rust.js#2]
Without `#include <string.h>`, I get this error:

``` c
../deps/api.cc: In member function ‘virtual void* ArrayBufferAllocator::Allocate(size_t)’:
../deps/api.cc:25:54: error: ‘memset’ was not declared in this scope
   return data == NULL ? data : memset(data, 0, length);
```

**Comment by yorkie** [comment]
Which gcc do you use?

**Comment by eddyb** [comment]
I tested with 4.9. I suspect that due to #3 it happens to work on OSX (but `memset` is not generally supposed to be found in `<string>`).

**Comment by yorkie** [comment]
Oh I see, that's because it's toy project of mine for now, so I just played around in my local machine....Thanks, will try to fix them.
