### ISSUE TITLE
Building broken completely everywhere other than OSX.

### ISSUE THREAD

**Issue by eddyb** [yorkie/rust.js#3]
It appears that the current setup is specialized to OSX:
A shared library is built (which fails on Linux because of missing `-fPIC`), followed by:

```
ln -f target.deps/Release/librustjs_deps.dylib /usr/local/lib/
```

`.dylib` is OSX-specific, it would be `.so` on Linux and `.dll` on Windows.

What's worse, a `Makefile` should _never_ do this.
Even on OSX, don't you need `sudo` to run this?
It's writing to `/usr/local/lib`, which shouldn't be owned by any user other than root.

A cleaner setup would be building a static library _from `src/build.rs`_ (instead of having a `Makefile` at all) and using that directly, without copying to system directories.

**Comment by yorkie** [comment]
Thanks, supported .so at 4aea947 for Linux, and will take a look at Windows build when v1.0.0 is released :)
